import LegalLayout from '../../components/layout/LegalLayout'
import { CONTACT_EMAIL } from '../../lib/legal'

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      title="Privacy Policy"
      subtitle="How TradeGradyzer collects, uses, shares and protects your personal data — and the rights you have over it."
    >
      <p className="lead">
        This Privacy Policy explains how <strong>TradeGradyzer</strong> ("TradeGradyzer", "we", "us"
        or "our") collects, uses, discloses and safeguards your personal data when you use our
        website, progressive web app and related services (together, the "Service"). It also
        describes your privacy rights and how the law protects you.
      </p>
      <p>
        We are committed to handling your data lawfully and transparently in line with the{' '}
        <strong>Nigeria Data Protection Act 2023 (NDPA)</strong>, and — where they apply to you — the
        <strong> EU General Data Protection Regulation (GDPR)</strong>, the{' '}
        <strong>UK GDPR</strong>, and the <strong>California Consumer Privacy Act as amended by the
        California Privacy Rights Act (CCPA/CPRA)</strong>. If you do not agree with this Policy,
        please do not use the Service.
      </p>

      <h2>1. Who we are (the data controller)</h2>
      <p>
        TradeGradyzer is the controller responsible for your personal data. We operate the Service
        from Nigeria. For any privacy matter — including to exercise your rights — contact us at{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
      <p>
        Where required, you may also designate this address for the attention of our "Data Protection
        contact". If we incorporate a registered company, the registered name and registration (RC)
        number will be published here.
      </p>

      <h2>2. The data we collect</h2>
      <p>We collect the following categories of personal data:</p>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Examples</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Account &amp; identity data</td>
            <td>Full name, email address, password (stored only as a salted hash), or your Google
              account identifier and basic profile if you sign in with Google.</td>
            <td>You; Google (if you use Google sign-in).</td>
          </tr>
          <tr>
            <td>Trading profile data</td>
            <td>Your trading style, preferred setups, risk appetite and markets traded, and whether
              you have completed onboarding.</td>
            <td>You.</td>
          </tr>
          <tr>
            <td>Content you submit</td>
            <td>Chart screenshots/images you upload, the instrument/pair, selected timeframes and any
              notes, plus the AI analysis results and history generated from them.</td>
            <td>You; generated by the Service.</td>
          </tr>
          <tr>
            <td>Subscription &amp; transaction data</td>
            <td>Plan, subscription status and expiry, currency, amount, and payment references. We do
              <strong> not</strong> receive or store your full card or bank details.</td>
            <td>You; our payment processor (Paystack).</td>
          </tr>
          <tr>
            <td>Usage &amp; technical data</td>
            <td>Usage events (e.g. number of analyses run, for quota and rate-limiting), device and
              browser type, approximate location/region inferred from IP, IP address, log and
              diagnostic data.</td>
            <td>Automatically collected.</td>
          </tr>
          <tr>
            <td>Communications</td>
            <td>Emails and support/complaint correspondence you send us.</td>
            <td>You.</td>
          </tr>
        </tbody>
      </table>
      <p>
        We do not intentionally collect special-category/sensitive personal data (such as health,
        biometric or government-ID data). Please do not include such information in chart notes or
        uploads.
      </p>

      <h2>3. How we use your data and our legal bases</h2>
      <p>Under the NDPA and GDPR we must have a lawful basis for each use of your data:</p>
      <table>
        <thead>
          <tr>
            <th>Purpose</th>
            <th>Legal basis (GDPR / NDPA)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Create and manage your account; authenticate logins.</td>
            <td>Performance of a contract with you.</td>
          </tr>
          <tr>
            <td>Provide the core Service — analysing your uploaded charts and returning a graded
              result tailored to your trading profile.</td>
            <td>Performance of a contract with you.</td>
          </tr>
          <tr>
            <td>Process payments and manage subscriptions, quotas and the lifetime-seat allocation.</td>
            <td>Performance of a contract; compliance with legal/accounting obligations.</td>
          </tr>
          <tr>
            <td>Maintain security, prevent fraud and abuse, and enforce rate limits and usage quotas.</td>
            <td>Legitimate interests (keeping the Service secure and available); legal obligation.</td>
          </tr>
          <tr>
            <td>Improve and debug the Service and understand aggregate usage.</td>
            <td>Legitimate interests (operating and improving our product).</td>
          </tr>
          <tr>
            <td>Respond to your enquiries, support requests and complaints.</td>
            <td>Legitimate interests; performance of a contract.</td>
          </tr>
          <tr>
            <td>Send service/transactional emails (e.g. email confirmation, password reset,
              subscription notices).</td>
            <td>Performance of a contract; legitimate interests.</td>
          </tr>
          <tr>
            <td>Send optional marketing, where offered.</td>
            <td>Consent (which you may withdraw at any time).</td>
          </tr>
          <tr>
            <td>Comply with the law and defend legal claims.</td>
            <td>Legal obligation; legitimate interests.</td>
          </tr>
        </tbody>
      </table>
      <p>
        Where we rely on legitimate interests, we have weighed those interests against your rights
        and freedoms. You can object to this processing — see Section 8.
      </p>

      <h2>4. Automated processing and AI</h2>
      <p>
        The core of the Service uses an automated AI model (currently Google's Gemini, accessed via
        Google's Generative Language API) to analyse the chart images you upload and produce a score,
        confidence grade, suggested levels and an indicative entry, stop and target. This output is
        generated automatically and is <strong>informational and educational only</strong>; it is
        not financial advice and produces no legal or similarly significant effect on you within the
        meaning of Article 22 GDPR. You remain solely responsible for any trading decision. See our{' '}
        <a href="/disclaimer">Disclaimer</a>.
      </p>

      <h2>5. Cookies and similar technologies</h2>
      <p>
        We use a small number of strictly necessary cookies and similar browser storage
        (localStorage/IndexedDB) to keep you signed in, maintain your session and remember
        essential preferences. These are required for the Service to function. We do not use
        third-party advertising cookies. As a progressive web app we may also cache assets on your
        device (a service worker) to enable offline loading; this does not track you.
      </p>

      <h2>6. Who we share your data with</h2>
      <p>
        We do not sell your personal data. We share it only with the processors and parties below,
        under contracts that require them to protect it and use it only on our instructions:
      </p>
      <table>
        <thead>
          <tr>
            <th>Recipient</th>
            <th>Purpose</th>
            <th>Where</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Supabase</td>
            <td>Authentication, database, file storage and serverless functions that run the Service.</td>
            <td>European Union (Ireland).</td>
          </tr>
          <tr>
            <td>Google (Gemini / Generative Language API)</td>
            <td>AI analysis of the chart images and prompts you submit.</td>
            <td>United States / global.</td>
          </tr>
          <tr>
            <td>Paystack</td>
            <td>Processing card/bank payments and verifying transactions.</td>
            <td>Nigeria / applicable region.</td>
          </tr>
          <tr>
            <td>Vercel</td>
            <td>Hosting and delivery of the website/app frontend.</td>
            <td>Global (CDN).</td>
          </tr>
        </tbody>
      </table>
      <p>
        We may also disclose data where required by law, to enforce our terms, to protect our rights,
        property or safety, or in connection with a merger, acquisition or sale of assets (in which
        case we will notify you).
      </p>

      <h2>7. International data transfers</h2>
      <p>
        Because our providers operate in the EU, the United States and elsewhere, your data may be
        transferred to and processed in countries other than your own. Where we transfer personal
        data out of Nigeria, the EU/EEA or the UK, we rely on an appropriate safeguard — such as the
        European Commission's Standard Contractual Clauses (and the UK Addendum), the provider's
        adequacy status where available, or an equivalent NDPA-recognised mechanism — to ensure your
        data remains protected.
      </p>

      <h2>8. Your data protection rights</h2>
      <p>
        Subject to the law that applies to you, you have the right to:
      </p>
      <ul>
        <li><strong>Access</strong> — obtain a copy of the personal data we hold about you.</li>
        <li><strong>Rectification</strong> — have inaccurate or incomplete data corrected.</li>
        <li><strong>Erasure</strong> — ask us to delete your data ("right to be forgotten").</li>
        <li><strong>Restriction</strong> — ask us to limit how we use your data.</li>
        <li><strong>Portability</strong> — receive your data in a portable, machine-readable format.</li>
        <li><strong>Objection</strong> — object to processing based on legitimate interests or to
          direct marketing.</li>
        <li><strong>Withdraw consent</strong> — where we rely on consent, withdraw it at any time
          (without affecting prior processing).</li>
        <li><strong>Lodge a complaint</strong> — with a supervisory authority (see Section 13).</li>
      </ul>
      <p>
        You can exercise most rights directly in the app (update your profile, or delete your
        account in Settings) or by emailing{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We will respond within the time
        required by law (generally one month under GDPR; 45 days under CCPA/CPRA, extendable once).
        We will not discriminate against you for exercising your rights, and exercising them is free
        unless a request is manifestly unfounded or excessive.
      </p>

      <h2>9. California privacy rights (CCPA/CPRA)</h2>
      <p>
        If you are a California resident, you have specific rights regarding your personal
        information:
      </p>
      <ul>
        <li><strong>Right to know</strong> the categories and specific pieces of personal
          information we collect, the sources, the purposes, and the categories of third parties with
          whom we share it (all described above).</li>
        <li><strong>Right to delete</strong> personal information we have collected, subject to legal
          exceptions.</li>
        <li><strong>Right to correct</strong> inaccurate personal information.</li>
        <li><strong>Right to opt out</strong> of the "sale" or "sharing" of personal information, and
          to limit the use of sensitive personal information.</li>
        <li><strong>Right to non-discrimination</strong> for exercising your rights.</li>
      </ul>
      <p>
        <strong>We do not "sell" your personal information and we do not "share" it for
        cross-context behavioural advertising</strong> as those terms are defined under the
        CCPA/CPRA, and we have not done so in the preceding 12 months. We therefore do not offer a
        "Do Not Sell or Share My Personal Information" link because it does not apply to us. We do not
        knowingly collect or sell the personal information of consumers under 16. You may exercise
        your California rights, or use an authorised agent to do so, by emailing{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>; we will verify your request using the
        account information we hold.
      </p>

      <h2>10. Data retention</h2>
      <p>
        We keep your personal data only for as long as necessary for the purposes set out in this
        Policy:
      </p>
      <ul>
        <li>Account, profile and analysis history — for as long as your account is active.</li>
        <li>Uploaded chart images — retained to display your analysis history; deleted when you
          delete the analysis or your account.</li>
        <li>Transaction and accounting records — for the period required by applicable tax and
          accounting law (typically up to 6 years).</li>
        <li>Security and log data — for a limited period necessary for security and abuse prevention.</li>
      </ul>
      <p>
        When you delete your account, we delete or irreversibly anonymise your personal data except
        where we must retain it to meet a legal obligation or to resolve disputes.
      </p>

      <h2>11. How we protect your data</h2>
      <p>
        We use appropriate technical and organisational measures to protect your data, including
        encryption in transit (HTTPS/TLS), hashed passwords, access controls and row-level security
        on our database, server-side enforcement of permissions and quotas, and reputable
        infrastructure providers. No method of transmission or storage is completely secure, so we
        cannot guarantee absolute security, but we work to protect your data and will notify you and
        the relevant authority of a personal data breach where the law requires.
      </p>

      <h2>12. Children's privacy</h2>
      <p>
        The Service is intended for adults and is <strong>not directed at anyone under 18</strong>.
        We do not knowingly collect personal data from children. If you believe a child has provided
        us with personal data, contact us and we will delete it.
      </p>

      <h2>13. Complaints and supervisory authorities</h2>
      <p>
        If you have a concern, please contact us first at{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> so we can try to resolve it (see our{' '}
        <a href="/complaints">Complaints Policy</a>). You also have the right to lodge a complaint
        with a data protection authority:
      </p>
      <ul>
        <li><strong>Nigeria</strong> — the Nigeria Data Protection Commission (NDPC).</li>
        <li><strong>EU/EEA</strong> — your local Data Protection Authority.</li>
        <li><strong>UK</strong> — the Information Commissioner's Office (ICO).</li>
        <li><strong>California</strong> — the California Privacy Protection Agency or the California
          Attorney General.</li>
      </ul>

      <h2>14. Changes to this Policy</h2>
      <p>
        We may update this Policy from time to time. When we make material changes we will update the
        "Last updated" date above and, where appropriate, notify you in the app or by email. Your
        continued use of the Service after changes take effect constitutes acceptance of the updated
        Policy.
      </p>

      <h2>15. Contact us</h2>
      <p>
        For any question about this Policy or your personal data, email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalLayout>
  )
}
