// One-shot Supabase provisioning via the Management API.
// Reads the sbp_ token from .supabase-token, applies the migration,
// then writes Project URL + anon key into .env.
//
// Usage: node scripts/supabase-setup.mjs <project-ref>

import { readFile, writeFile } from 'node:fs/promises'

const ref = process.argv[2]
if (!ref) {
  console.error('Usage: node scripts/supabase-setup.mjs <project-ref>')
  process.exit(1)
}

const token = (await readFile('.supabase-token', 'utf8')).trim()
const API = 'https://api.supabase.com/v1'
const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }

async function runSql(sql) {
  const res = await fetch(`${API}/projects/${ref}/database/query`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ query: sql }),
  })
  const text = await res.text()
  if (!res.ok) throw new Error(`SQL failed (${res.status}): ${text}`)
  return text
}

// 1. Apply migration
console.log('→ Applying schema migration…')
const migration = await readFile('supabase/migrations/0001_init.sql', 'utf8')
await runSql(migration)
console.log('✓ Schema applied (profiles, analyses, RLS, charts bucket, triggers).')

// 2. Fetch API keys + build .env
console.log('→ Fetching API keys…')
const keysRes = await fetch(`${API}/projects/${ref}/api-keys`, { headers })
if (!keysRes.ok) throw new Error(`api-keys failed (${keysRes.status}): ${await keysRes.text()}`)
const keys = await keysRes.json()

const anon =
  keys.find((k) => k.name === 'anon')?.api_key ||
  keys.find((k) => k.type === 'publishable')?.api_key ||
  keys.find((k) => k.name === 'publishable')?.api_key
if (!anon) throw new Error('Could not find an anon/publishable key in: ' + JSON.stringify(keys.map((k) => k.name)))

const url = `https://${ref}.supabase.co`
const env = `# Auto-generated by scripts/supabase-setup.mjs
VITE_SUPABASE_URL=${url}
VITE_SUPABASE_ANON_KEY=${anon}
VITE_ANALYZE_FUNCTION=analyze-chart
VITE_USE_MOCK_ANALYZER=false
`
await writeFile('.env', env, 'utf8')
console.log('✓ Wrote .env with Project URL + anon key.')
console.log('\nProject URL:', url)
console.log('Done.')
